apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: "1.8.2"
    helm:
      values: |
        alloy:
          configMap:
            content: |
              otelcol.receiver.otlp "default" {
                grpc {
                  endpoint = "0.0.0.0:4317"
                }
                http {
                  endpoint = "0.0.0.0:4318"
                }
                output {
                  metrics = [otelcol.processor.k8sattributes.default.input]
                  logs    = [otelcol.processor.k8sattributes.default.input]
                  traces  = [otelcol.processor.k8sattributes.default.input]
                }
              }

              otelcol.processor.k8sattributes "default" {
                output {
                  metrics = [otelcol.exporter.otlphttp.mimir.input]
                  logs    = [otelcol.exporter.otlphttp.loki.input]
                  traces  = [otelcol.exporter.otlphttp.tempo.input]
                }
                extract {
                  metadata = ["k8s.namespace.name", "k8s.pod.name", "k8s.node.name"]
                }
              }

              otelcol.exporter.otlphttp "mimir" {
                client {
                  endpoint = "http://mimir-distributed-nginx.observability.svc.cluster.local:4318"
                  tls {
                    insecure = true
                  }
                }
              }

              otelcol.exporter.otlphttp "loki" {
                client {
                  endpoint = "http://loki-gateway.observability.svc.cluster.local:4318"
                  tls {
                    insecure = true
                  }
                }
              }

              otelcol.exporter.otlphttp "tempo" {
                client {
                  endpoint = "http://tempo.observability.svc.cluster.local:4318"
                  tls {
                    insecure = true
                  }
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
