apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "10.5.15"
    helm:
      values: |
        adminPassword: "changeme"
        service:
          type: ClusterIP
        plugins:
          - grafana-pyroscope-datasource
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Mimir
              type: prometheus
              url: http://mimir-gateway.observability.svc.cluster.local:80/prometheus
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki.observability.svc.cluster.local:3100
              access: proxy
            - name: Tempo
              type: tempo
              url: http://tempo.observability.svc.cluster.local:3200
              access: proxy
            - name: Pyroscope
              type: grafana-pyroscope-datasource
              url: http://pyroscope.observability.svc.cluster.local:4040
              access: proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
