apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "argocd-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Argo CD"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - REPLACE_WITH_ARGOCD_DOMAIN
      secretName: argocd-tls
  rules:
    - host: REPLACE_WITH_ARGOCD_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
